### ISSUE TITLE
[OOB 5.10] Incorrect platform name in mbed_lib.json

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/qspif-blockdevice#10]
mbed_lib.json lists the target: DISCO_L475VG
```
       "DISCO_L475VG": {
             "QSPI_FREQ": "8000000",
        },

```
the actual target name is DISCO_L475VG_IOT01A

**Comment by MarceloSalazar** [comment]
FYI @offirko

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSTOR-653

**Comment by MarceloSalazar** [comment]
@maclobdell can you please verify the fix?

**Comment by maclobdell** [comment]
Works now.  Thanks.  Closing this issue.
