### ISSUE TITLE
Remove redundant duplicate code

### ISSUE THREAD

**Issue by deepikabhavnani** [ARMmbed/qspif-blockdevice#16]
Parameter check is performed in init and constructor, since error cannot be returned from constructor code is not serving any purpose.

https://github.com/ARMmbed/qspif-blockdevice/blob/master/QSPIFBlockDevice.cpp#L116
https://github.com/ARMmbed/qspif-blockdevice/blob/master/QSPIFBlockDevice.cpp#L127

Check in init should be good enough for this case

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSTOR-660

**Comment by offirko** [comment]
@deepikabhavnani -  I know it seems like a duplicate log but the actual point of trying to add a new csel is at c'tor. I found it important to add an 'info'/'error' level log  at this exact point in case in debug/development someone reads the log at c'tor even before init() was called.

**Comment by deepikabhavnani** [comment]
I still find it to be redundant, as we always do init and not leave it just after constructor. All the commits in this PR (https://github.com/ARMmbed/qspif-blockdevice/pull/19)  are for suggestion / cleanup, you can pick specific commit and not merge entire PR. As I might not get time to update again, it up to you.
