### ISSUE TITLE
Times out before block erase can finish

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/qspif-blockdevice#3]
The maximum timeout to wait on the flash becoming ready is currently statically set to one second: https://github.com/ARMmbed/qspif-blockdevice/blob/8ea8e83c348463de9b0832a46c83d0addfaf934e/QSPIFBlockDevice.cpp#L73

However, this is not nearly enough to cover the maximum block erase time from some flash devices. Consider for example the Macronix MX25R series ([datasheet](http://www.macronix.com/Lists/Datasheet/Attachments/7406/MX25R3235F,%20Wide%20Range,%2032Mb,%20v1.5.pdf)). They can take up to 3 seconds for a 32K erase, and 3.5 seconds for a 64K erase. Beyond that, a Chip Erase would take anywhere between 26 and 120 seconds.

Can this max timeout value be made configurable through e.g. the mbed config system, or increased to a more sane default value?

**Comment by stevew817** [comment]
@offirko Shall I just make the change myself and submit a PR?

**Comment by offirko** [comment]
@stevew817 - thanks for spotting this. It was actually meant to be 10000 to support up to 64KB sector size erase + some margin. Note that chip erase command is currently not supported, so it should be changed to 10000. I'd appreciate it if you could make the change yourself ! Thanks again.

**Comment by stevew817** [comment]
Was fixed by #5
